# Generated by Django 5.2.1 on 2025-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableappTrust',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tableapp_trust',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TableappTrustguideline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1025)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_url', models.CharField(blank=True, max_length=1025, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('medical_speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=1025, null=True)),
                ('viewcount', models.IntegerField()),
                ('authors', models.CharField(blank=True, max_length=1025, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=255, null=True)),
                ('review_date', models.CharField(blank=True, max_length=255, null=True)),
                ('version_number', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tableapp_trustguideline',
                'managed': False,
            },
        ),
    ]
