# Generated by Django 5.2 on 2025-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks_credit_political', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpoliticalrisk',
            name='credit_score',
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='counterparty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='country_of_counterparty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='country_of_insured',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='country_of_risk',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='creation_date',
            field=models.DateField(blank=True, help_text='Business logic creation date, distinct from record creation time.', null=True),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='inception_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='insured',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='product',
            field=models.CharField(blank=True, choices=[('trade_credit', 'Trade Credit'), ('trade_finance', 'Trade Finance'), ('project_finance', 'Project Finance')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='score',
            field=models.IntegerField(blank=True, help_text='Specific risk score for this entry.', null=True),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('bound', 'Bound'), ('approving', 'Approving'), ('new_deal', 'New Deal'), ('approved', 'Approved')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='unstructured_data',
            field=models.JSONField(blank=True, help_text='Store unstructured third-party data before processing.', null=True),
        ),
    ]
