# Generated by Django 5.2 on 2025-05-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks_credit_political', '0002_remove_creditpoliticalrisk_credit_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='source_record_id',
            field=models.CharField(blank=True, db_index=True, help_text='The unique ID of the record in the source system.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditpoliticalrisk',
            name='source_system',
            field=models.CharField(blank=True, db_index=True, help_text='Identifier for the external system where the record originated.', max_length=255, null=True),
        ),
    ]
