# Generated by Django 5.2 on 2025-05-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks_credit_political', '0004_creditpoliticalrisk_attachment_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpoliticalrisk',
            name='attachment_metadata',
        ),
    ]
